spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_security
    username: root
    password: Rediffmail@1409
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql:true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect